### ISSUE TITLE
New _COMMA_OR_WHITESPACE regex pattern causes AddrFormatError if list of addresses separated by space is used

### ISSUE THREAD

**Issue by kaleposhobios** [mozilla-services/pyramid_ipauth#8]
When I use `parse_ip_set` with an address string separated by spaces, such as is done in the unit tests:
"192.168.0.1 123.123.0.1"

An AddrFormatError is raised. This is because when the new regex pattern splits a space-separated string, one of the values in the resulting array is ' '.
```python
_COMMA_OR_WHITESPACE = re.compile(r"(,\s*|\s+)")
result = _COMMA_OR_WHITESPACE.split("192.168.0.1 123.123.0.1")
result = ["192.168.0.1", " ", "123.123.0.1"]
```

Does this not happen for you? I was considering a PR like this:
```python
    for ipspec in _COMMA_OR_WHITESPACE.split(ipaddrs):
      if not ipspec.strip():
         continue
       # The string "local" maps to all local addresses on the machine.
       if ipspec == "local":

```
But if this is not happening for you, let's discuss. Thank you!

**Comment by rfk** [comment]
@kaleposhobios quite right, I'm getting test failures that look to be caused by this issue.  Not sure why I wasn't seeing them before when I merged this :-(

**Comment by rfk** [comment]
I adjusted the regex and added some tests in https://github.com/mozilla-services/pyramid_ipauth/pull/9, could you please take a look and see if that fixes the problem for you?

**Comment by kaleposhobios** [comment]
@rfk It works now for me, the new regex looks great. Your regex-fu is far better than mine :)

**Comment by rfk** [comment]
Thanks for checking, I'll cut a new release shortly.
